Repository moquette-io/moquette, pull requests merged in 2023-03, with the labels that each got.

#733 Avoid to use deprecated PERSISTENT_STORE_PROPERTY_NAME property
  broker/src/main/java/io/moquette/broker/Server.java
Labels: bugfix, v0.17.0

#723 Fix/segment persistent queues
  broker/src/main/java/io/moquette/broker/PostOffice.java
Labels: bugfix, v0.17.0

#735 Avoid to drain on an already closed/destroyed session
  broker/src/main/java/io/moquette/broker/MQTTConnection.java
  broker/src/main/java/io/moquette/broker/Session.java
  broker/src/main/java/io/moquette/broker/SessionRegistry.java
Labels: bugfix, v0.17.0

#721 Implement and use a Session data storage
  broker/pom.xml
  broker/src/main/java/io/moquette/broker/ISessionsRepository.java
  broker/src/main/java/io/moquette/broker/Server.java
  broker/src/main/java/io/moquette/broker/Session.java
  broker/src/main/java/io/moquette/broker/SessionRegistry.java
  broker/src/main/java/io/moquette/persistence/H2Builder.java
  broker/src/main/java/io/moquette/persistence/H2SessionsRepository.java
  broker/src/main/java/io/moquette/persistence/MemorySessionsRepository.java
  broker/src/test/java/io/moquette/broker/MQTTConnectionConnectTest.java
  broker/src/test/java/io/moquette/broker/MQTTConnectionPublishTest.java
  broker/src/test/java/io/moquette/broker/PostOfficeInternalPublishTest.java
  broker/src/test/java/io/moquette/broker/PostOfficePublishTest.java
  broker/src/test/java/io/moquette/broker/PostOfficeSubscribeTest.java
  broker/src/test/java/io/moquette/broker/PostOfficeUnsubscribeTest.java
  broker/src/test/java/io/moquette/broker/SessionRegistryTest.java
  broker/src/test/java/io/moquette/broker/SessionTest.java
Labels: persistence

#738 Switched boolean flag to immediate flushing to integer
  ChangeLog.txt
  broker/src/main/java/io/moquette/BrokerConstants.java
  broker/src/main/java/io/moquette/broker/BrokerConfiguration.java
  broker/src/main/java/io/moquette/broker/MQTTConnection.java
  broker/src/main/java/io/moquette/broker/NewNettyAcceptor.java
  broker/src/main/java/io/moquette/broker/Server.java
  broker/src/test/java/io/moquette/broker/BrokerConfigurationTest.java
  broker/src/test/java/io/moquette/broker/MQTTConnectionConnectTest.java
  broker/src/test/java/io/moquette/broker/MQTTConnectionPublishTest.java
  broker/src/test/java/io/moquette/broker/PostOfficeInternalPublishTest.java
  broker/src/test/java/io/moquette/broker/PostOfficePublishTest.java
  broker/src/test/java/io/moquette/broker/PostOfficeSubscribeTest.java
  broker/src/test/java/io/moquette/broker/PostOfficeUnsubscribeTest.java
  broker/src/test/java/io/moquette/broker/SessionRegistryTest.java
  broker/src/test/java/io/moquette/broker/SessionTest.java
  distribution/src/main/resources/moquette.conf
Labels: feature, v0.17.0

#725 Moved session calls to the session-queue
  broker/src/main/java/io/moquette/broker/MQTTConnection.java
Labels: v0.17.0

#740 Fixes Embedded test project, missed to implement an interface method
  embedding_moquette/src/main/java/io/moquette/testembedded/EmbeddedLauncher.java
Labels: v0.17.0

#741 Fixed synthax error in Bash launcher
  distribution/src/main/scripts/moquette.sh
Labels: v0.17.0
