Repository moquette-io/moquette, pull requests merged in 2024-04, with the labels that each got.

#823 Update message expiry remaining time and drop queued messages if expired
  ChangeLog.txt
  broker/src/main/java/io/moquette/broker/MQTTConnection.java
  broker/src/main/java/io/moquette/broker/MoquetteIdleTimeoutHandler.java
  broker/src/main/java/io/moquette/broker/Session.java
  broker/src/main/java/io/moquette/broker/SessionRegistry.java
  broker/src/main/java/io/moquette/persistence/SegmentPersistentQueue.java
  broker/src/main/java/io/moquette/persistence/SegmentedPersistentQueueSerDes.java
  broker/src/test/java/io/moquette/integration/mqtt5/AbstractServerIntegrationTest.java
  broker/src/test/java/io/moquette/integration/mqtt5/MessageExpirationTest.java
  broker/src/test/java/io/moquette/integration/mqtt5/SubscriptionOptionsTest.java
  broker/src/test/java/io/moquette/integration/mqtt5/TestUtils.java
  broker/src/test/java/io/moquette/persistence/SegmentPersistentQueueTest.java
  broker/src/test/java/io/moquette/testclient/Client.java
Labels: enhancement, mqtt5

#824 Updated will publishing to contains also the message expire property
  ChangeLog.txt
  broker/src/main/java/io/moquette/broker/ISessionsRepository.java
  broker/src/main/java/io/moquette/broker/PostOffice.java
  broker/src/test/java/io/moquette/integration/mqtt5/ConnectTest.java
  broker/src/test/java/io/moquette/integration/mqtt5/MessageExpirationTest.java
  broker/src/test/java/io/moquette/integration/mqtt5/SubscriptionWithIdentifierTest.java
  broker/src/test/java/io/moquette/integration/mqtt5/TestUtils.java
  broker/src/test/java/io/moquette/testclient/Client.java
Labels: enhancement, mqtt5

#827 Avoid decomposition of Publish fields into method params
  ChangeLog.txt
  broker/src/main/java/io/moquette/broker/MQTTConnection.java
  broker/src/main/java/io/moquette/broker/PostOffice.java
  broker/src/test/java/io/moquette/broker/PostOfficePublishTest.java
  broker/src/test/java/io/moquette/broker/PostOfficeSubscribeTest.java
  broker/src/test/java/io/moquette/broker/PostOfficeUnsubscribeTest.java
Labels: mqtt5, refactory

#828 Use SerDes for H2 storage of retained messages
  broker/src/main/java/io/moquette/broker/MemoryRetainedRepository.java
  broker/src/main/java/io/moquette/broker/PostOffice.java
  broker/src/main/java/io/moquette/broker/RetainedMessage.java
  broker/src/main/java/io/moquette/persistence/H2RetainedRepository.java
Labels: mqtt5

#832 Fixed #831: changed several cases where a shared readerIndex was changed
  broker/src/main/java/io/moquette/broker/DebugUtils.java
  broker/src/main/java/io/moquette/broker/Utils.java
  broker/src/main/java/io/moquette/persistence/SegmentedPersistentQueueSerDes.java
  broker/src/test/java/io/moquette/persistence/SegmentedPersistentQueueSerDesTest.java
Labels: v0.18.0, memory leak

#836 Fixed empty shared subscriptions list remaining forever
  broker/src/main/java/io/moquette/broker/subscriptions/CTrieSubscriptionDirectory.java
  broker/src/main/java/io/moquette/persistence/H2SubscriptionsRepository.java
Labels: v0.18.0, memory leak
